Modernize the travis-ci build script.
The new script enables doctest and hlint testing, "cabal check", and
verification of the "sdist"-generated release tarball. We build our code with
the respective latest version of every major GHC release since GHC 7.10.x. (We
cannot use earlier versions because they don't have time-1.5.x.)

hlint generates plenty of warnings, which we currently all disable to make the
build succeed. We'll fix those issues one after another, but I'd rather do so
while having a working CI.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,75 +1,123 @@
-# NB: don't set `language: haskell` here
+# This Travis job script has been generated by a script via
+#
+#   runghc make_travis_yml_2.hs '--doctest' '--doctest-options=-package=Cabal' '--hlint' '-o' '.travis.yml' 'cgi.cabal'
+#
+# For more information, see https://github.com/haskell-CI/haskell-ci
+#
+language: c
+sudo: false
 
-# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
-env:
- - GHCVER=7.4.2 CABALVER=1.20 CABALFLAGS='' TEST=''
- - GHCVER=7.4.2 CABALVER=1.22 CABALFLAGS='' TEST=''
- - GHCVER=7.4.2 CABALVER=1.24 CABALFLAGS='' TEST=''
- - GHCVER=7.6.3 CABALVER=1.20 CABALFLAGS='' TEST=''
- - GHCVER=7.6.3 CABALVER=1.22 CABALFLAGS='' TEST=''
- - GHCVER=7.6.3 CABALVER=1.24 CABALFLAGS='' TEST=''
- - GHCVER=7.8.4 CABALVER=1.20 CABALFLAGS='' TEST='' #ghc 7.8 versions, see note about alex and happy
- - GHCVER=7.8.4 CABALVER=1.22 CABALFLAGS='' TEST='' #ghc 7.8 versions, see note about alex and happy
- - GHCVER=7.8.4 CABALVER=1.24 CABALFLAGS='' TEST='' #ghc 7.8 versions, see note about alex and happy
- - GHCVER=7.10.3 CABALVER=1.22 CABALFLAGS='' TEST=''
- - GHCVER=7.10.3 CABALVER=1.24 CABALFLAGS='' TEST='yes'
- - GHCVER=head CABALVER=1.24 CABALFLAGS='' TEST='yes'
- - GHCVER=head CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
- - GHCVER=7.4.2 CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
- - GHCVER=7.6.3 CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
- - GHCVER=7.8.4 CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
+git:
+  submodules: false  # whether to recursively clone submodules
 
-# Note: the distinction between `before_install` and `install` is not important.
-before_install:
- - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - cabal --version
- - cabal update
- - cabal install -j -O2 packdeps
+cache:
+  directories:
+    - $HOME/.cabal/packages
+    - $HOME/.cabal/store
 
-install:
- - if [ "$TEST" == 'yes' ]; then
-      cabal install $CABALFLAGS --only-dependencies --enable-tests --enable-benchmarks;
-   else
-      cabal install $CABALFLAGS --only-dependencies --enable-benchmarks;
-   fi
+before_cache:
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/build-reports.log
+  # remove files that are regenerated by 'cabal update'
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/00-index.*
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/*.json
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.cache
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar
+  - rm -fv $HOME/.cabal/packages/hackage.haskell.org/01-index.tar.idx
 
-# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
-script:
- - if [ "$TEST" == 'yes' ]; then
-      cabal configure $CABALFLAGS --enable-benchmarks --enable-tests -v2;
-   else
-      cabal configure $CABALFLAGS --enable-benchmarks -v2;
-   fi
- - cabal build   # this builds all libraries and executables (including tests/benchmarks)
- - if [ "$TEST" == 'yes' ]; then
-    cabal test;
-   fi
- - cabal check
- - cabal sdist   # tests that a source-distribution can be generated
- - cabal --version | grep --quiet '1.22';
-   if [ $? -eq 0 ]; then
-      find . -name '*.cabal' | xargs cabal exec packdeps;
-   fi
-
-# The following scriptlet checks that the resulting source distribution can be built & installed
- - export SRC_TGZ=$(cabal-$CABALVER info . | awk '{print $2 ".tar.gz";exit}') ;
-   cd dist/;
-   if [ -f "$SRC_TGZ" ]; then
-      cabal install "$SRC_TGZ";
-   else
-      echo "expected '$SRC_TGZ' not found";
-      exit 1;
-   fi
+  - rm -rfv $HOME/.cabal/packages/head.hackage
 
 matrix:
-  fast_finish: true
-  allow_failures:
-    - env: GHCVER=head CABALVER=1.24 CABALFLAGS='' TEST='yes' # see section about GHC HEAD snapshots
-    - env: GHCVER=head CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
-    - env: GHCVER=7.4.2 CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
-    - env: GHCVER=7.6.3 CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
-    - env: GHCVER=7.8.4 CABALVER=1.24 CABALFLAGS='--allow-newer' TEST='yes'
-    - env: GHCVER=7.10.3 CABALVER=1.24 CABALFLAGS='' TEST='yes'
+  include:
+    - compiler: "ghc-8.6.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.6.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.4.4"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.4.4], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.2.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.2.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-8.0.2"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-8.0.2], sources: [hvr-ghc]}}
+    - compiler: "ghc-7.10.3"
+    # env: TEST=--disable-tests BENCH=--disable-benchmarks
+      addons: {apt: {packages: [ghc-ppa-tools,cabal-install-2.4,ghc-7.10.3], sources: [hvr-ghc]}}
+
+before_install:
+  - HC=${CC}
+  - HCPKG=${HC/ghc/ghc-pkg}
+  - unset CC
+  - ROOTDIR=$(pwd)
+  - mkdir -p $HOME/.local/bin
+  - "PATH=/opt/ghc/bin:/opt/ghc-ppa-tools/bin:$HOME/local/bin:$PATH"
+  - HCNUMVER=$(( $(${HC} --numeric-version|sed -E 's/([0-9]+)\.([0-9]+)\.([0-9]+).*/\1 * 10000 + \2 * 100 + \3/') ))
+  - echo $HCNUMVER
+
+install:
+  - cabal --version
+  - echo "$(${HC} --version) [$(${HC} --print-project-git-commit-id 2> /dev/null || echo '?')]"
+  - BENCH=${BENCH---enable-benchmarks}
+  - TEST=${TEST---enable-tests}
+  - HADDOCK=${HADDOCK-true}
+  - UNCONSTRAINED=${UNCONSTRAINED-true}
+  - NOINSTALLEDCONSTRAINTS=${NOINSTALLEDCONSTRAINTS-false}
+  - GHCHEAD=${GHCHEAD-false}
+  - travis_retry cabal update -v
+  - "sed -i.bak 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config"
+  - rm -fv cabal.project cabal.project.local
+  - grep -Ev -- '^\s*--' ${HOME}/.cabal/config | grep -Ev '^\s*$'
+  - (cd /tmp && echo '' | cabal new-repl -w ${HC} --build-dep fail)
+  - if [ $HCNUMVER -ge 80000 ]; then cabal new-install -w ${HC} -j2 --symlink-bindir=$HOME/.local/bin doctest --constraint='doctest ==0.16.*'; fi
+  - if [ $HCNUMVER -eq 80602 ]; then cabal new-install -w ${HC} -j2 --symlink-bindir=$HOME/.local/bin hlint --constraint='hlint ==2.1.*'; fi
+  - "printf 'packages: \".\"\\n' > cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- cgi | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  - if [ -f "./configure.ac" ]; then
+      (cd "." && autoreconf -i);
+    fi
+  - rm -f cabal.project.freeze
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} --project-file="cabal.project" --dep -j2 all
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks --project-file="cabal.project" --dep -j2 all
+  - rm -rf .ghc.environment.* "."/dist
+  - DISTDIR=$(mktemp -d /tmp/dist-test.XXXX)
+
+# Here starts the actual work to be performed for the package under test;
+# any command which exits with a non-zero exit code causes the build to fail.
+script:
+  # test that source-distributions can be generated
+  - cabal new-sdist all
+  - mv dist-newstyle/sdist/*.tar.gz ${DISTDIR}/
+  - cd ${DISTDIR} || false
+  - find . -maxdepth 1 -name '*.tar.gz' -exec tar -xvf '{}' \;
+  - "printf 'packages: cgi-*/*.cabal\\n' > cabal.project"
+  - touch cabal.project.local
+  - "if ! $NOINSTALLEDCONSTRAINTS; then for pkg in $($HCPKG list --simple-output); do echo $pkg  | grep -vw -- cgi | sed 's/^/constraints: /' | sed 's/-[^-]*$/ installed/' >> cabal.project.local; done; fi"
+  - cat cabal.project || true
+  - cat cabal.project.local || true
+  # this builds all libraries and executables (without tests/benchmarks)
+  - cabal new-build -w ${HC} --disable-tests --disable-benchmarks all
+
+  # build & run tests, build benchmarks
+  - cabal new-build -w ${HC} ${TEST} ${BENCH} all
+  - if [ "x$TEST" = "x--enable-tests" ]; then cabal new-test -w ${HC} ${TEST} ${BENCH} all; fi
+
+  # doctest
+  - if [ $HCNUMVER -ge 80000 ]; then (cd cgi-* && doctest -package=Cabal .); fi
+
+  # hlint
+  - if [ $HCNUMVER -eq 80602 ]; then (cd cgi-* && hlint .); fi
+
+  # cabal check
+  - (cd cgi-* && cabal check)
+
+  # haddock
+  - if $HADDOCK; then cabal new-haddock -w ${HC} ${TEST} ${BENCH} all; else echo "Skipping haddock generation";fi
+
+  # Build without installed constraints for packages in global-db
+  - if $UNCONSTRAINED; then rm -f cabal.project.local; echo cabal new-build -w ${HC} --disable-tests --disable-benchmarks all; else echo "Not building without installed constraints"; fi
+
+# REGENDATA ["--doctest","--doctest-options=-package=Cabal","--hlint","-o",".travis.yml","cgi.cabal"]
+# EOF
